name: Build project
on:
  create:
    tags:
      - 'v*'
jobs:
    build:
      runs-on: windows-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
           fetch-depth: 0
        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1.0.2
        - name: Restore NuGet
          run: nuget restore GKutt.sln
        - name: Run MSBuild
          run: msbuild GKutt.csproj /p:Configuration=Release
        - name: Create release
          uses: ncipollo/release-action@v1.8.6
          with:
            artifacts: "bin/Release/GKutt.exe"
            token: ${{ secrets.GITHUB_TOKEN }}
