name: Build project
on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
jobs:
    build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
          with:
           fetch-depth: 0
        - uses: microsoft/setup-msbuild@v1.0.2
        - run: msbuild GKutt.csproj /t:Restore;Build /p:Configuration=Release
        - uses: ncipollo/release-action@v1.8.6
          with:
            artifacts: "bin/Release/GKutt.exe"
            token: ${{ secrets.GITHUB_TOKEN }}
